service: auth-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: "*"

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    platform: node
    concurrency: 10
